### ISSUE TITLE
Emitter test does not check data correctly

### ISSUE THREAD

**Issue by Kaiziron** [RareSkills/huff-puzzles#15]
The 2nd uint256 in the Value event is not indexed
```
event Value(uint256 indexed, uint256);
```

But bool checkData in expectEmit() is false, which does not check for data correctly
https://github.com/RareSkills/huff-puzzles/blob/main/test/Emitter.t.sol#L21
```
 vm.expectEmit(true, true, false, false);
```

**Comment by AmadiMichael** [comment]
Thanks for the feedback, this has been fixed [here](https://github.com/RareSkills/huff-puzzles/pull/20)

**Comment by AmadiMichael** [comment]
Thanks for the feedback, this has been fixed [here](https://github.com/RareSkills/huff-puzzles/pull/20)
