### ISSUE TITLE
Assert argument does not match string description

### ISSUE THREAD

**Issue by calvbore** [RareSkills/huff-puzzles#7]
https://github.com/RareSkills/huff-puzzles/blob/7fb7a3cdf10400f316b06017d533bad1598876f9/test/SimulateArray.t.sol#L74

String says expected value is `2` but arg passed into the assert is `1`.

**Comment by RareSkills** [comment]
Closed with #8

**Comment by calvbore** [comment]
> Closed with #8

@RareSkills This changed the assertion argument to 2, but i think the proper behaviour is still to check that the length is 1. The error string should be changed to match it.
